In [1]:
# Import libraries - numpy, pandas, and scikit-learn
import pandas as pd
import numpy as np

In [2]:
# Question 1 - Get Pandas version
pd.__version__
# 3.0.6 is my version

'3.0.6'

In [3]:
# View the data - 2026 Car Fuel Efficiency data
pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [4]:
# Read the data
cars = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [5]:
# Question 2
# How many records are in the data set?
# In other words, how many rows are in the data frame?
len(cars)
# Get 10000

10000

In [6]:
# Question 3
# How many fuel types are presented in the data set?
cars.fuel_type.unique()
# 'Gasoline', 'Diesel', and 'Hybrid', so 3

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
# Question 4
# How many columns in the data set have missing values?
cars.isnull().sum()
# horsepower and acceleration are the only columns that do, so 2

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
# Question 5
# What's the maximum fuel efficiency of cars from Asia?
# First, need to examine the origins column
cars.origin.unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [9]:
# Now that we know there's only one Asia value, we can find the max fuel efficiency
cars[cars.origin == "Asia"].fuel_efficiency_mpg.max()
# It's 41.2 mpg

np.float64(41.2)

In [10]:
# Question 6
# (1) Find the median value of the horsepower column in the data set.
# The median is included in the summary statistics when using describe
cars.horsepower.describe()
# The median is the 50th percentile, which is 254

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [11]:
# Question 6
# (2) Next, calculate the most frequent value of the same horsepower column.
# Can do this with the mode() function
cars.horsepower.mode()
# The most frequent value is 252

0    252.0
Name: horsepower, dtype: float64

In [ ]:
# Question 6
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.
# Has it changed?
cars.horsepower.fillna(252).describe()
# The median value changed to 252, so yes. It decreased from 254.
# It is clear the missing values were filled because the count increased to 10000 and the std decreased.

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower, dtype: float64

In [13]:
# Question 7
# Select all the cars from Asia. Select only columns vehicle_weight and model_year. 
# Select the first 7 values. Get the underlying NumPy array. Let's call it X.

# The head function returns the first five rows by default, but it can easily be changed to 7.
cars[cars.origin == "Asia"][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
# Question 7
# Get the underlying NumPy array. Let's call it X.

# Can do this using values.
X = cars[cars.origin == "Asia"][['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [15]:
# Question 7
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

# Can do this using dot()
XTX = (X.T).dot(X)
XTX

# X.T is 2x7 and X is 7x2, so XTX should be 2x2, which it is.

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [16]:
# Question 7
# Invert XTX

# Can do this using np.linalg.inv()
np.linalg.inv(XTX)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [20]:
# Question 7
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = (np.linalg.inv(XTX).dot(X.T)).dot(y)
w

# The inverse of XTX is 2x2 and X.T is 2x7, so the resulting matrix should be 2x7.
# Multiplying that by y, which is 7x1, should result in something that's 2x1, which it is.

array([0.13644777, 0.2327492 ])

In [22]:
# Question 7
# What's the sum of all the elements of the result?

sum(w)
# Get approximately 0.369

np.float64(0.36919696904925486)