In [1]:
# Import libraries - numpy, pandas, matplotlib, seaborn, and scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Make it so plots display in the notebook
%matplotlib inline

In [4]:
# Read and view the data - 2026 Lead-Scoring data. Call it leads.
leads = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")
leads.tail()
# 5000 data points
# Target variable is converted - 1 if a lead signed up for the platform, and 0 if not

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [6]:
# Data Preparation
# Check if the missing values are presented in the features.
# If there are missing values:
# For categorical features, replace them with 'NA'
# For numerical features, replace with with 0.0

# Now check for missing values
leads.isnull().sum()
# lead_source, industry, employment_status, location, annual_income, and lead_score all have missing values.

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [31]:
# Check the variables to determine if they are categorical or numeric
pd.DataFrame([leads.dtypes, leads.nunique()], index=["Data Type", "Unique Values"])

# From the results of this and the tail() examination earlier, can determine the following:
# categorical variables: lead_source, industry, employment_status, location
# numeric variables: annual_income, lead_score

# None of the categorical variables are binary, aside from the target

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
Data Type,str,str,str,str,float64,int64,int64,float64,int64
Unique Values,6,7,5,6,4314,7,14,100,2

In [32]:
# Save these variable to fill to lists
categorical_to_fill = ['lead_source', 'industry', 'employment_status', 'location']
numeric_to_fill = ['annual_income', 'lead_score']

# For each categorical variable to fill, replace missing values with 'NA' as instructed
leads[categorical_to_fill] = leads[categorical_to_fill].fillna('NA')

# For each numeric variable to fill, replace missing values with 0.0 as instructed
leads[numeric_to_fill] = leads[numeric_to_fill].fillna(0.0)

In [33]:
# Question 1
# What is the most frequent observation (mode) for the column industry?

# Can do this by calling describe() on the column in question
leads.industry.describe()
# The most frequenct industry is technology

count           5000
unique             7
top       technology
freq            1173
Name: industry, dtype: object

In [ ]:
# Question 2
# Create the correlation matrix for the numerical features of your dataset. 
# In a correlation matrix, you compute the correlation coefficient between every pair of features.
# What are the two features that have the biggest correlation?