In [2]:
# Import libraries - numpy, pandas, matplotlib, seaborn, and scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split

# Make it so plots display in the notebook
%matplotlib inline

In [4]:
# Read and view the data - 2026 Lead-Scoring data. Same as HW3. Call it leads.
leads = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")
leads.tail()
# 5000 data points
# Target variable is converted - 1 if a lead signed up for the platform, and 0 if not

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
4995,organic_search,education,employed,asia,45834.0,2,2,0.37,1
4996,NaN,technology,employed,north_america,84831.0,2,5,0.51,0
4997,organic_search,finance,employed,asia,53636.0,4,6,0.75,1
4998,referral,technology,employed,africa,69430.0,4,8,0.79,1
4999,referral,technology,employed,europe,81355.0,6,11,0.99,1

In [5]:
# Data Preparation
# Check if the missing values are presented in the features.
# If there are missing values:
# For categorical features, replace them with 'NA'
# For numerical features, replace with with 0.0

# Now check for missing values
leads.isnull().sum()
# lead_source, industry, employment_status, location, annual_income, and lead_score all have missing values.

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [6]:
# Check the variables to determine if they are categorical or numeric
pd.DataFrame([leads.dtypes, leads.nunique()], index=["Data Type", "Unique Values"])

# From the results of this and the tail() examination earlier, can determine the following:
# categorical variables: lead_source, industry, employment_status, location
# numeric variables: annual_income, lead_score

# None of the categorical variables are binary, aside from the target.

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
Data Type,str,str,str,str,float64,int64,int64,float64,int64
Unique Values,5,6,4,5,4313,7,14,99,2

In [7]:
# Save these variables to lists based on whether they are categorical or numeric.
categorical_vars = ['lead_source', 'industry', 'employment_status', 'location']
numeric_vars = ['annual_income', 'number_of_courses_viewed', 'interaction_count', 'lead_score']


# For each categorical variable, replace missing values with 'NA' as instructed
leads[categorical_vars] = leads[categorical_vars].fillna('NA')

# For each numeric variable, replace missing values with 0.0 as instructed
leads[numeric_vars] = leads[numeric_vars].fillna(0.0)

In [8]:
# Split the data into three parts as instructed:
df_full_train, df_test = train_test_split(leads, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [ ]:
# Question 1: ROC AUC feature importance

# ROC AUC could also be used to evaluate feature importance of numerical variables. Let's do that.
# For each numerical variable, use it as score (aka prediction) and compute the AUC with the y variable as ground truth.
# Use the training dataset for that.
# If your AUC is < 0.5, invert this variable by putting "-" in front (e.g. -df_train['balance'])
# AUC can go below 0.5 if the variable is negatively correlated with the target variable. 
# You can change the direction of the correlation by negating this variable - then negative correlation becomes positive.

# Which numerical variable (among the following 4) has the highest AUC?

#